Atolcd bug fixes : Offline mode
sigmah-dev/sigmah pull request #101
Opened 2017-06-26 10:04 UTC by ftavin

This commits handle offline mode for contacts and LayoutGroupIteration.
The first commit also adds tomcat in docker-compose file to help dealing with offline mode dev using docker (instructions in commit message)

2017-06-26 14:06 UTC, osarrat commented
Wow !
That's a great work !

While I will assess that it does functionally the job, could you improve a bit code quality as specified by this Codacy report : https://www.codacy.com/app/osarrat/sigmah/pullRequest?prid=733364 ? (mostly unused imports to remove)

2017-06-26 14:33 UTC, ghost requested changes
I had a quick review, also, I second the "really long methods" spotted by Codacy.

2017-06-26 14:33 UTC, numero-six commented on docker-compose.yml
> +    - ./target/sigmah-2.2-SNAPSHOT/:/usr/local/tomcat/webapps/sigmah/
Can you find a way without having the version `2.2-SNAPSHOT`?

2017-06-26 14:33 UTC, numero-six commented on docker-compose.yml
> +    - ./target/sigmah-2.2-SNAPSHOT/:/usr/local/tomcat/webapps/sigmah/
The documentation you put in the commit message is interesting, could you put it in a comment in this file?

2017-06-26 14:33 UTC, numero-six commented on src/main/java/org/sigmah/shared/dto/element/FlexibleElementDTO.java
> +				if (ElementTypeEnum.CONTACT_LIST == this.getElementType() && Profiler.INSTANCE.getApplicationStateManager().getLastState() == ApplicationState.OFFLINE) {
This piece of code

```java
Profiler.INSTANCE.getApplicationStateManager().getLastState() == ApplicationState.OFFLINE
```

is copy-pasted everywhere (sometimes in a method, sometimes not). Can you factorize in a single method somewhere in `Profiler.INSTANCE` or in `ApplicationStateManager`? I guess what you are actually looking for is the flag `ApplicationStateManager#online`

2017-06-26 14:33 UTC, numero-six commented on src/main/java/org/sigmah/client/ui/presenter/contact/ContactDetailsPresenter.java
> +		if (!iterationChanges.isEmpty()) {
Too long, please break in smaller methods (or maybe extract anonymous class to inner?)

2017-07-03 13:07 UTC, osarrat commented
Thanks @ftavin for those last modifications. Would it be possible for you to also take into account @numero-six requested changes?

2017-08-09 08:35 UTC, numero-six commented on docker-tomcat.sh
> +            -v $PWD/target/sigmah-2.2-SNAPSHOT/:/usr/local/tomcat/webapps/sigmah/:ro \
Please, remove hard-coded `2.2-SNAPSHOT`.

You can start your script with something like

```bash
# gives SIGMAH_VERSION="2.2-SNAPSHOT"
SIGMAH_VERSION=`mvn --quiet -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec`
```

See also https://stackoverflow.com/questions/3545292/how-to-get-maven-project-version-to-the-bash-command-line

2017-09-07 09:48 UTC, osarrat commented
Hi @numero-six 
Is this PR mergeable according to you ?
Best

2017-09-07 15:46 UTC, numero-six commented
Codacy has good points but nothing like an error.

Does it ends the 2.2 developments? If yes I would be happy to tag the final `2.2`.

2017-09-09 06:55 UTC, osarrat commented
Thanks @numero-six ! I merge it now.
Regarding making it the final v2.2, I'll come back on this issue next week.

2017-09-09 06:55 UTC, merged

2017-09-13 11:06 UTC, osarrat commented
Hi @numero-six and @ftavin 

I wish to discuss with @ftavin on whether this v2.2-rc6 should be the final v2.2 or not.
So the point is not concluded today, and since we need to publish this v2.2-rc6 for a usage by CARE today, we can consider that a v2.2-rc6 will be released.
We will see later on if we releease this v2.2-rc6 also as the final v2.2.

Best !

2017-09-13 12:17 UTC, numero-six commented
Hi! `2.2-rc6` tag published

2017-09-13 12:54 UTC, osarrat commented
Great, thank you !