[WIP] Issue#1075:  Project global export empty if not requested by first PioneerAdmin
sigmah-dev/sigmah pull request #90
Opened 2017-04-09 14:48 UTC by indianauthority97

2017-04-10 15:44 UTC, indianauthority97 commented
Hi, I have assessed the possible causes for why this bug may be occurring. @osarrat please review and mention if I seem to be on the right track. Thanks!

Possible Cause #1: In the class org.sigmah.server.security.impl.AccessRights , I could not find any sperm permission entry for the tokens org.sigmah.shared.command.GetOrgUnits, org.sigmah.shared.command.GetContacts, project-exports and EXPORT#EXPORT_GLOBAL

(this is based on the warnings generated in the server logs, but I am not sure because they seem to be generated for both the PioneerAdministrator and the created user.) Here are the logs :

[WARN ] {09/04/2017 16:23:30.175} [btpool0-6] o.s.s.security.impl.AccessRights - No security permission can be found for token 'org.sigmah.shared.command.GetOrgUnits'. Did you forget to declare corresponding 'sperm'?
[WARN ] {09/04/2017 16:23:30.224} [btpool0-7] o.s.s.security.impl.AccessRights - No security permission can be found for token 'org.sigmah.shared.command.GetContacts'. Did you forget to declare corresponding 'sperm'?
[WARN ] {09/04/2017 16:25:51.839} [btpool0-4] o.s.s.security.impl.AccessRights - No security permission can be found for token 'project-exports'. Did you forget to declare corresponding 'sperm'?
[WARN ] {09/04/2017 16:25:56.682} [btpool0-4] o.s.s.security.impl.AccessRights - No security permission can be found for token 'EXPORT#EXPORT_GLOBAL'. Did you forget to declare corresponding 'sperm'?


Possible Cause #2: While creating PioneerAdministrator, we set the values in the table ("INSERT INTO global_permission...") the values 'GLOBAL_EXPORT' by default.
I am not sure if this permission is also granted to any other user that the PioneerAdministrator creates.


Possible cause #3: In the table GlobalExportSettings, 

The class main.java.org.sigmah.shared.command.GetGlobalExportSettings is constructed with a boolean param retrieveProjectModels. 
It is called by the method onPageRequest of class org.sigmah.client.ui.presenter.admin.ParametersAdminPresenter

Here is the called line :

		// Retrieves configured export format.
		dispatch.execute(new GetGlobalExportSettings(auth().getOrganizationId(), false), new CommandResultHandler<GlobalExportSettingsDTO>() {

Why is it always called with the boolean parameter "false" ?

2017-04-11 12:35 UTC, osarrat requested changes
Revise your commit by using the existing log mechanism.

2017-04-11 12:35 UTC, osarrat commented on src/main/java/org/sigmah/server/dao/impl/GlobalExportHibernateDAO.java
> +import org.mortbay.log.Log;
It would better if you replicate the log mechanism used in other part of the codebase.

2017-04-11 12:37 UTC, osarrat commented
Hi @indianauthority97 ,

Regarding the cause of this bug, you seem on the right track ! I don't know what is the cause of this bug, but continue to investigate, and you should be able to find the right cause among the three you imagine

2017-04-11 12:56 UTC, indianauthority97 commented on src/main/java/org/sigmah/server/dao/impl/GlobalExportHibernateDAO.java
> +import org.mortbay.log.Log;
Realised my mistake as soon as I ran it. Thanks!

2017-04-11 14:04 UTC, indianauthority97 commented
Status : Investigated PossibleCause #3 : this is not the reason, it behaves the same way for both users.

More research : Identified the place where the difference is happening.

org.sigmah.server.dao.impl.ProjectHibernateDAO

[Here, the PioneerAdminstrator export call is getting a list of all my projects, but the created user is fetching zero projects i.e. empty list of Collection<ProjectModel> pmodels in the method getProjects.

This could be related to :

org.sigmah.server.domain.util.EntityFilters
org.sigmah.server.domain.util.DomainFilters.disableUserFilter(em());

Still working on it.

2017-04-12 16:13 UTC, indianauthority97 commented
Hi @osarrat I updated the issue. Please review. Thanks!

2017-04-12 16:41 UTC, indianauthority97 commented
Hi @osarrat , I updated the issue. Please review it. Thanks!

2017-04-26 10:16 UTC, osarrat approved these changes

2017-04-26 10:22 UTC, osarrat commented
Hi @indianauthority97 , congrats for this bug fix !
I have tested it locally, and your work does actually fix the bug ! Congratulations !

But I won't merge your PR in the end, because while fixing the issue #1081, I have actually made exactly the same modifications that you have done, and thus your code modification is not necessary, but your analysis and work on the fix is useful because you have found the reason of behind this bug.

2017-04-26 10:22 UTC, closed without merging